### ISSUE TITLE
Highlighted bar at bottom is unreadable

### ISSUE THREAD

**Issue by RodBarnes** [hardinfo2/hardinfo2#24] opened 2024-04-20 02:33 UTC
NOTE: Maybe this is due to using dark mode?  Awesome app, BTW.

I clicked the "GPU Drawing" entry at the bottom.  It went through the benchmark test and completed successfully.  But, at the bottom, below the right-window, is a banner in yellow with white text and an [x] to close it.  The text is unreadable.  See [here](https://i.postimg.cc/X72QYLLM/hardinfo2-highlight-bottom.png).

**Comment by hwspeedy** [comment] 2024-04-20 06:10
Hi @RodBarnes,

Thanx for reporting - It's a duplicate of fixed issue https://github.com/hardinfo2/hardinfo2/issues/22

Will be in next release.

**Closed by hwspeedy** 2024-04-20 06:10 UTC
